### ISSUE TITLE
Failed to run cron jobs

### ISSUE THREAD

**Issue by dkamm** [SergeyTsalkov/brooce#12]
I followed the steps in the quick start without any issues.  I then tried to add the following cron job: 
```
$ redis-cli HSET "brooce:cron:jobs" "cron-long-sleeper" "* * * * * queue:common sleep 120"                                                                                          
(integer) 1
```
It was added to redis but it is not being run by brooce nor is it viewable in the `cron jobs` tab.

redis-server version is v=3.0.6

my `brooce.conf`:
```
{
  "cluster_name": "brooce",
  "global_job_options": {
    "timeout": 3600,
    "maxtries": 1
  },
  "web": {
    "addr": ":8080",
    "certfile": "",
    "keyfile": "",
    "username": "admin",
    "password": "ddshrlvt",
    "no_auth": false,
    "disable": false
  },
  "file_output_log": {
    "enable": false
  },
  "redis_output_log": {
    "drop_done": false,
    "drop_failed": false,
    "expire_after": 10
  },
  "job_results": {
    "drop_done": false,
    "drop_failed": false
  },
  "redis": {
    "host": "localhost:6379",
    "password": "",
    "db": 0
  },
  "suicide": {
    "enable": false,
    "command": "",
    "time": 0
  },
  "queues": [
    {
      "name": "common",
      "workers": 1
    },
    {
      "name": "parallel",
      "workers": 5
    }
  ],
  "path": ""
}
```

**Comment by SergeyTsalkov** [comment]
My bet is you're using an outdated version. I actually forgot to update the quick start instructions to show that version 1.2.0 is available. I just updated those now, so if you follow it again and get the latest version, it should work.

Don't forget to delete the brooce.conf file first, since some things about it have changed. It'll re-create it with a proper new structure.
